---
- name: Instala o Puppet Agent com Debian
  apt:
    name: puppet-agent
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Instala o Puppet Agent com RedHat
  yum:
    name: puppet-agent
    state: present
  when: ansible_os_family == 'RedHat'

- name: Inicia o Puppet Agent
  service:
    name: puppet
    state: started
    enabled: yes
