---
- name: Instala o Puppet Server
  apt:
    name: puppetserver
    state: present
    update_cache: yes

- name: Inicia o puppetserver
  service:
    name: puppetserver
    state: started
    enabled: yes
