---
- name: Instalação do Docker
  hosts: docker

  tasks:
    - name: Remover versões antigas
      apt:
        name: "{{ item }}"
        state: absent
      with_items:
        - docker
        - docker-engine
        - docker.io

