---
- name: Instala pacotes
  hosts: docker
  tasks:
    - apt:
        name: "{{ item }}"
        state: present
      with_items:
        - vim
        - hollywood
        - cowsay
        - cmatrix
